import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DINOv3_MODEL_PATH = Path(
    os.environ.get(
        "DINOV3_MODEL_PATH", "./pretrained/dinov3-vitl16-local"
    )
)

OUTPUT_ROOT = Path(
    os.environ.get("OUTPUT_ROOT", "./outputs")
)

DATA_CFG = dict(
    image_size=224,
    max_frames=8,
)

DATA_ROOT = Path(os.environ.get("LDM_DATA_ROOT", "../data"))

DATASET_CFG = {
    "agiworld": dict(
        format="lerobot",
        root_dir=DATA_ROOT / "agiworld_merged_all",
        data_type="robot",
        video_key="observation.images.head",
        action_key="action.ee_delta",
        use_for_reconstruction=True,
        use_for_action_alignment=True,
        repair_data_file_index=True,
        sample_weight=3.0,
        alignment_sample_weight=3.0,
        human_require_all_action_dims_nonzero=False,
        window_stride=1,
    ),
    "egodex": dict(
        format="lerobot",
        root_dir=DATA_ROOT / "egodex_merged_all",
        data_type="human",
        video_key="observation.images.stereo_left",
        action_key="action",
        use_for_reconstruction=True,
        use_for_action_alignment=True,
        repair_data_file_index=True,
        sample_weight=2.0,
        alignment_sample_weight=2.0,
        human_require_all_action_dims_nonzero=True,
        window_stride=1,
    ),
    "egoverse": dict(
        format="lerobot",
        root_dir=DATA_ROOT / "egoverse_lerobot_merged",
        data_type="human",
        video_key="observation.images.front_1",
        action_key="action",
        use_for_reconstruction=True,
        use_for_action_alignment=True,
        repair_data_file_index=True,
        sample_weight=2.0,
        alignment_sample_weight=1.0,
        human_require_all_action_dims_nonzero=False,
        window_stride=1,
    ),
    "ego4d": dict(
        format="lerobot",
        root_dir=DATA_ROOT / "ego4d_merged_all",
        data_type="human",
        video_key="observation.images.ego",
        action_key=None,
        use_for_reconstruction=True,
        use_for_action_alignment=False,
        repair_data_file_index=True,
        sample_weight=1.0,
        window_stride=1,
    ),
    "xper": dict(
        format="lerobot",
        root_dir=DATA_ROOT / "xper_merged",
        data_type="human",
        video_key="observation.images.stereo_left",
        action_key=None,
        use_for_reconstruction=True,
        use_for_action_alignment=False,
        repair_data_file_index=True,
        sample_weight=1.0,
        window_stride=1,
    ),
    "RoboMind2.0_franka_p1": dict(
        format="lerobot",
        root_dir=DATA_ROOT / "RoboMind2.0_franka_p1",
        data_type="robot",
        video_key="observation.images.camera_top",
        action_key=None,
        use_for_reconstruction=True,
        use_for_action_alignment=False,
        repair_data_file_index=True,
        sample_weight=1.0,
        window_stride=1,
    ),
    "RoboMind2.0_franka_p2": dict(
        format="lerobot",
        root_dir=DATA_ROOT / "RoboMind2.0_franka_merged_p2",
        data_type="robot",
        video_key="observation.images.camera_top",
        action_key=None,
        use_for_reconstruction=True,
        use_for_action_alignment=False,
        repair_data_file_index=True,
        sample_weight=1.0,
        window_stride=1,
    ),
    "RoboMind2.0_franka_part": dict(
        format="lerobot",
        root_dir=DATA_ROOT / "RoboMind2.0_franka_part_merged",
        data_type="robot",
        video_key="observation.images.camera_front",
        action_key=None,
        use_for_reconstruction=True,
        use_for_action_alignment=False,
        repair_data_file_index=True,
        sample_weight=1.0,
        window_stride=1,
    ),
    "RoboMind2.0_agilex": dict(
        format="lerobot",
        root_dir=DATA_ROOT / "RoboMind2.0_agilex_merged",
        data_type="robot",
        video_key="observation.images.camera_front",
        action_key=None,
        use_for_reconstruction=True,
        use_for_action_alignment=False,
        repair_data_file_index=True,
        sample_weight=1.0,
        window_stride=1,
    ),
    "RoboMind2.0_ur": dict(
        format="lerobot",
        root_dir=DATA_ROOT / "RoboMind2.0_ur_merged",
        data_type="robot",
        video_key="observation.images.camera_top",
        action_key=None,
        use_for_reconstruction=True,
        use_for_action_alignment=False,
        repair_data_file_index=True,
        sample_weight=0.5,
        window_stride=1,
    ),
    "Robomind1.0_franka": dict(
        format="lerobot",
        root_dir=DATA_ROOT / "Robomind1.0_franka_merged",
        data_type="robot",
        video_key="observation.images.top",
        action_key=None,
        use_for_reconstruction=True,
        use_for_action_alignment=False,
        repair_data_file_index=True,
        sample_weight=0.5,
        window_stride=1,
    ),
}

VAL_DATASET_CFG = DATASET_CFG

LEROBOT_DATALOADER_CFG = dict(
    action_sample_ratio=0.3,
    action_zero_eps=1e-6,
    train_epoch_size=100_000,
    val_epoch_size=512,
    val_windows_per_dataset=256,
    batch_level_same_episode=True,
    batch_start_jitter=128,
    frame_strides=[1, 2, 3, 4],
    frame_stride_weights=[0.4, 0.3, 0.2, 0.1],
    rotation_accumulate="sum",
)

MODEL_CFG = dict(
    dim=1024,
    image_size=DATA_CFG["image_size"],
    patch_size=16,
    channels=3,
    enc_depth=6,
    dec_depth=6,
    dim_head=64,
    heads=16,
    attn_dropout=0.0,
    ff_dropout=0.1,
    quant_dim=32,
    codebook_size=8,
    code_seq_len=16,
    encode_deltas=False,
    discarding_threshold=0.015,
    spatial_enc_type="dinov3_vitl16_local",
    dinov3_model_path=str(DINOv3_MODEL_PATH),
    freeze_spatial_encoder=True,
    semantic_loss_weight=1.0,
    feature_norm_loss_weight=0.01,
    use_lpips_loss=False,
    lpips_loss_weight=0.0,
    use_flow_loss=False,
    flow_loss_weight=0.0,
    flow_loss_kickin_step=10_000,
    flow_loss_warmup_steps=3_000,
    max_codebook_update_step=15_000,
    codebook_usage_loss_weight=0.005,
    token_entropy_loss_weight=0.0001,
    action_dim=14,            
    align_kickin_step=15_000,
    align_loss_weight=0.2,
    align_action_translation_scale=0.01,
    align_action_rotation_scale=0.08,
    align_action_gripper_scale=0.02,
)

TRAIN_CFG = dict(
    num_train_steps=100_000,
    batch_size=8,
    val_batch_size=2,
    lr=3e-5,
    pretrained_init_lr_mult_factor=0.1,
    weight_decay=0.01,
    grad_accum_every=1,
    max_grad_norm=1.0,
    lr_scheduler="cosine",
    lr_warmup_steps=5_000,
    min_lr=1e-6,
    save_model_every=2000,
    save_milestone_every=5000,
    val_every_n_steps=200,
    num_val_batches_to_log=2,
    num_workers=6,
    prefetch_factor=2,
    pin_memory=True,
    log_every_n_steps=50,
    metrics_shard_steps=1000,
)
